baseURL = 'https://glassdarkly.dev/'
locale = 'en-us'
title = 'Glass Darkly'
theme = 'glass'
disableKinds = ['taxonomy', 'term']

[params]
  description = 'for now we see in part.'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']

[services]
  [services.rss]
    limit = 20
